services:
  postgres:
    container_name: db
    image: postgres
    # env_file:
    #   - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
